name: afterthought
channels:
  - conda-forge
dependencies:
  - python = 3.8
  - pip>19.0
  - numpy
  - scipy
  - pandas
  - jupyter
  - jupyterlab
  - bqplot
  - matplotlib
  - voila
  - empyrical
  - tqdm
